# Generated by Django 3.2.9 on 2021-11-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=30, null=True)),
                ('editorial', models.CharField(max_length=200)),
                ('NumPags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=200)),
                ('fecPrestamo', models.DateTimeField(auto_now=True)),
                ('feacDevolucion', models.DateTimeField(null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.libro')),
            ],
        ),
    ]
