# Generated by Django 3.2.9 on 2021-11-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_prestamo_fecprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
